### PR TITLE
Port unit-tests to main and generate tests

### PR DESCRIPTION
**Pull request by ryansteakley**
**Description of your changes:**
Port over unit-tests to the main branch and generate tests for the applicable manifests found in the `awsconfigs/common` directory.
- Add directories of the kustomization packages we are modifiyng/own to `generate_test.py`
- Run these new generated tests in `tests/unit-tests/Makefile `
- Non-auto generated files
  - `generate_tests.py`
  - `Makefile`
  - `test_util.py`
**Checklist:**
- [X] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Review by goswamig — APPROVED** [review]

**Review by surajkota — COMMENTED** [review]
Taking long to review even if I leave out the `test_data/expected` need more time to ramp up

if we are using the same framework as upstream, I am wondering if it is possible to keep only the diff here. Integration tests and overlays depend on the upstream repo to be available locally, Can we use the same approach and only keep a diff we own?

**Comment by surajkota** [comment]
PR mentions `awsconfigs/common`. will tests for `awsconfigs/apps` be a separate PR?

**Comment by ryansteakley** [comment]
> PR mentions `awsconfigs/common`. will tests for `awsconfigs/apps` be a separate PR? It will be good to keep it separate

Yes, it will be a separate pr, this was to port things under common since they are all aws related.

**Comment by mbaijal** [comment]
Can you link to the original PR in the description since that PR had easier to read diffs for reference.

**Review by mbaijal — APPROVED** [review]
LGTM since this is a copy of the previous PRs changes with path changes.

**Pull request merged**
