### PR TITLE
Add Terraform S3 backend support

### PR DESCRIPTION
**Pull request by rrrkharse**
**Which issue is resolved by this Pull Request:**

**Description of your changes:**
Adds documentation on how to use AWS S3 as a remote Terraform backend.

**Testing:**
Manual testing on 2 different hosts using the same S3 backend.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by AlexandreBrown** [comment]
Will this fix https://github.com/awslabs/kubeflow-manifests/issues/635 ?

**Comment by rrrkharse** [comment]
> will local backup still exist?

Yes

**Comment by rrrkharse** [comment]
> Will this fix #635 ?

Yes, it will allow the separate runners to reference the same tfstate stored in S3

**Review by ryansteakley — APPROVED** [review]
nice work

**Pull request merged**
