### PR TITLE
Helm chart vanilla v1.6.0

### PR DESCRIPTION
**Pull request by jsitu777**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
- added all Vanilla Helm charts for KF v1.6.0

**Testing:**
- [ ] Unit tests pass
- [x] e2e tests pass
- Details about new tests (If this PR adds a new feature)
- Details about any manual tests performed
```
pytest tests/test_sanity_portforward.py -s -q --region eu-west-1 --keepsuccess --installation_option helm

tests/test_sanity_portforward.py::TestSanity::test_kfp_experiment upstream directory already exists, skipping clone ...
Installation Option: helm
Deployment Option: vanilla
AWS-telemetry Option: enable
=================================================================
     You are installing kubeflow vanilla deployment with helm    
=================================================================
==========Installing cert-manager==========
"jetstack" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "eks" chart repository
Update Complete. ⎈Happy Helming!⎈
NAME: cert-manager
LAST DEPLOYED: Fri Sep  9 12:03:54 2022
NAMESPACE: cert-manager
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
cert-manager v1.9.1 has been deployed successfully!

In order to begin issuing certificates, you will need to set up a ClusterIssuer
or Issuer resource (for example, by creating a 'letsencrypt-staging' issuer).

More information on the different types of issuers and how to configure them
can be found in our documentation:

https://cert-manager.io/docs/configuration/

For information on how to configure cert-manager to automatically provision
Certificates for Ingress resources, take a look at the `ingress-shim`
documentation:

https://cert-manager.io/docs/usage/ingress/
Waiting for cert-manager pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app.kubernetes.io/instance in (cert-manager)' --timeout=240s -n cert-manager
pod/cert-manager-7b8d75c477-vb22p condition met
pod/cert-manager-cainjector-6cd8d7f84b-njbv8 condition met
pod/cert-manager-webhook-64d76db6c-77j7m condition met
All cert-manager pods are running!
==========Installing kubeflow-roles==========
NAME: kubeflow-roles
LAST DEPLOYED: Fri Sep  9 12:05:56 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
All kubeflow-roles pods are running!
==========Installing kubeflow-issuer==========
NAME: kubeflow-issuer
LAST DEPLOYED: Fri Sep  9 12:06:15 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
All kubeflow-issuer pods are running!
==========Installing istio-1-14==========
W0909 12:07:02.284088   78565 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0909 12:07:03.884968   78565 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0909 12:08:03.675698   78565 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0909 12:08:03.682460   78565 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
NAME: istio-1-14
LAST DEPLOYED: Fri Sep  9 12:06:54 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for istio-1-14 pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (istio-ingressgateway, istiod)' --timeout=240s -n istio-system
pod/istio-ingressgateway-6668f9548d-b8h4b condition met
pod/istiod-6678f9548b-l9j6j condition met
All istio-1-14 pods are running!
==========Installing kubeflow-namespace==========
NAME: kubeflow-namespace
LAST DEPLOYED: Fri Sep  9 12:08:22 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
All kubeflow-namespace pods are running!
==========Installing dex==========
NAME: dex
LAST DEPLOYED: Fri Sep  9 12:08:36 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for dex pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (dex)' --timeout=240s -n auth
pod/dex-559dbcd758-k45sv condition met
All dex pods are running!
==========Installing cluster-local-gateway==========
NAME: cluster-local-gateway
LAST DEPLOYED: Fri Sep  9 12:09:06 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for cluster-local-gateway pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (cluster-local-gateway)' --timeout=240s -n istio-system
pod/cluster-local-gateway-55ff4696f4-x47nz condition met
All cluster-local-gateway pods are running!
==========Installing knative-serving==========
NAME: knative-serving
LAST DEPLOYED: Fri Sep  9 12:09:56 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for knative-serving pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app.kubernetes.io/name in (knative-serving)' --timeout=240s -n knative-serving
pod/activator-7c5cd78566-lgwfh condition met
pod/autoscaler-98487645d-5kzb2 condition met
pod/controller-7546f544b7-68p9v condition met
pod/domain-mapping-5d56bfc7d-h64qm condition met
pod/domainmapping-webhook-696559d49c-zz2mr condition met
pod/net-istio-controller-c4d469c-9pw56 condition met
pod/net-istio-webhook-855bcb6747-s4tzw condition met
pod/webhook-59f9fdd446-vs9sj condition met
All knative-serving pods are running!
==========Installing knative-eventing==========
W0909 12:12:19.133743   78834 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0909 12:13:44.686286   78834 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
NAME: knative-eventing
LAST DEPLOYED: Fri Sep  9 12:12:10 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for knative-eventing pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app.kubernetes.io/name in (knative-eventing)' --timeout=240s -n knative-eventing
pod/eventing-controller-8457bd9747-g9wvt condition met
pod/eventing-webhook-69986cfb5d-xhnhb condition met
All knative-eventing pods are running!
==========Installing oidc-authservice==========
NAME: oidc-authservice
LAST DEPLOYED: Fri Sep  9 12:13:58 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for oidc-authservice pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (authservice)' --timeout=240s -n istio-system
pod/authservice-0 condition met
All oidc-authservice pods are running!
==========Installing kubeflow-istio-resources==========
NAME: kubeflow-istio-resources
LAST DEPLOYED: Fri Sep  9 12:14:34 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
All kubeflow-istio-resources pods are running!
==========Installing kserve==========
NAME: kserve
LAST DEPLOYED: Fri Sep  9 12:15:02 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for kserve pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (kserve)' --timeout=240s -n kubeflow
pod/kserve-controller-manager-0 condition met
All kserve pods are running!
==========Installing models-web-app==========
NAME: models-web-app
LAST DEPLOYED: Fri Sep  9 12:16:11 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for models-web-app pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'kustomize.component in (kserve-models-web-app)' --timeout=240s -n kubeflow
pod/kserve-models-web-app-5878544ffd-bqn7f condition met
All models-web-app pods are running!
==========Installing central-dashboard==========
NAME: central-dashboard
LAST DEPLOYED: Fri Sep  9 12:16:43 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for central-dashboard pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (centraldashboard)' --timeout=240s -n kubeflow
pod/centraldashboard-6c6f7c7cfb-zbh9b condition met
All central-dashboard pods are running!
==========Installing aws-secrets-manager==========
component aws-secrets-manager is not applicable for deployment option: vanilla
==========Installing kubeflow-pipelines==========
NAME: kubeflow-pipelines
LAST DEPLOYED: Fri Sep  9 12:17:40 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for kubeflow-pipelines pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'application-crd-id in (kubeflow-pipelines)' --timeout=240s -n kubeflow
pod/cache-server-56d94f5d78-t29bz condition met
pod/kubeflow-pipelines-profile-controller-5d98fd7b4f-tbvhl condition met
pod/metacontroller-0 condition met
pod/metadata-envoy-deployment-5b685dfb7f-brxbx condition met
pod/metadata-grpc-deployment-f8d68f687-7kcfp condition met
pod/metadata-writer-d6498d6b4-7zrkq condition met
pod/minio-5b65df66c9-4l2xn condition met
pod/ml-pipeline-687f7d69d5-zlxsw condition met
pod/ml-pipeline-persistenceagent-5854f86f8b-rsx7x condition met
pod/ml-pipeline-scheduledworkflow-5dddbf664f-2f7vd condition met
pod/ml-pipeline-ui-6bdfc6dbcd-tmd86 condition met
pod/ml-pipeline-viewer-crd-85f6fd557b-sl8mt condition met
pod/ml-pipeline-visualizationserver-7c4885999-4rkjl condition met
pod/mysql-5c7f79f986-2xdc7 condition met
pod/workflow-controller-6b9b6c5b46-vn29k condition met
All kubeflow-pipelines pods are running!
==========Installing admission-webhook==========
NAME: admission-webhook
LAST DEPLOYED: Fri Sep  9 12:22:39 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for admission-webhook pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (poddefaults)' --timeout=240s -n kubeflow
pod/admission-webhook-deployment-594bf75487-p4xqp condition met
All admission-webhook pods are running!
==========Installing jupyter-web-app==========
NAME: jupyter-web-app
LAST DEPLOYED: Fri Sep  9 12:23:12 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for jupyter-web-app pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (jupyter-web-app)' --timeout=240s -n kubeflow
pod/jupyter-web-app-deployment-6c88fd8b58-rg8d2 condition met
All jupyter-web-app pods are running!
==========Installing notebook-controller==========
NAME: notebook-controller
LAST DEPLOYED: Fri Sep  9 12:23:56 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for notebook-controller pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (notebook-controller)' --timeout=240s -n kubeflow
pod/notebook-controller-deployment-57fbfc57c8-v5cx6 condition met
All notebook-controller pods are running!
==========Installing volumes-web-app==========
NAME: volumes-web-app
LAST DEPLOYED: Fri Sep  9 12:24:48 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for volumes-web-app pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (volumes-web-app)' --timeout=240s -n kubeflow
pod/volumes-web-app-deployment-7d7d45b645-tv99m condition met
All volumes-web-app pods are running!
==========Installing training-operator==========
NAME: training-operator
LAST DEPLOYED: Fri Sep  9 12:25:37 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for training-operator pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'control-plane in (kubeflow-training-operator)' --timeout=240s -n kubeflow
pod/training-operator-6c9f6fd894-7qwnh condition met
All training-operator pods are running!
==========Installing katib==========
NAME: katib
LAST DEPLOYED: Fri Sep  9 12:26:28 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for katib pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'katib.kubeflow.org/component in (controller, db-manager, ui)' --timeout=240s -n kubeflow
pod/katib-controller-75b988dccc-l842t condition met
pod/katib-db-manager-5d46869758-dqzlr condition met
pod/katib-ui-766d5dc8ff-7lrpd condition met
All katib pods are running!
==========Installing tensorboards-web-app==========
NAME: tensorboards-web-app
LAST DEPLOYED: Fri Sep  9 12:27:25 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for tensorboards-web-app pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (tensorboards-web-app)' --timeout=240s -n kubeflow
pod/tensorboards-web-app-deployment-74b86b7c98-6fvpm condition met
All tensorboards-web-app pods are running!
==========Installing tensorboard-controller==========
NAME: tensorboard-controller
LAST DEPLOYED: Fri Sep  9 12:27:56 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for tensorboard-controller pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (tensorboard-controller)' --timeout=240s -n kubeflow
pod/tensorboard-controller-deployment-698db6955b-ccptn condition met
All tensorboard-controller pods are running!
==========Installing profiles-and-kfam==========
NAME: profiles-and-kfam
LAST DEPLOYED: Fri Sep  9 12:29:02 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for profiles-and-kfam pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'kustomize.component in (profiles)' --timeout=240s -n kubeflow
pod/profiles-deployment-55fcfdb64d-sc2c2 condition met
All profiles-and-kfam pods are running!
==========Installing user-namespace==========
NAME: user-namespace
LAST DEPLOYED: Fri Sep  9 12:29:52 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
All user-namespace pods are running!
==========Installing ingress==========
component ingress is not applicable for deployment option: vanilla
==========Installing alb-controller==========
component alb-controller is not applicable for deployment option: vanilla
==========Installing aws-authservice==========
component aws-authservice is not applicable for deployment option: vanilla
skip
==========Installing aws-telemetry==========
W0909 12:30:09.468651   79415 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0909 12:30:10.132396   79415 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
NAME: aws-telemetry
LAST DEPLOYED: Fri Sep  9 12:30:04 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
All aws-telemetry pods are running!
Saved key: installation_path value: ./resources/installation_config/vanilla.yaml in metadata file /Users/jsitu/Dev/Bugbash/kubeflow-manifests/tests/e2e/.metadata/metadata-1662751810457859000.json
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
Handling connection for 8080

--------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------
INFO     root:_client.py:457 Creating experiment experiment-1cfks1odf8.
PASSED
tests/test_sanity_portforward.py::TestSanity::test_run_pipeline 
--------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------
INFO     root:_client.py:457 Creating experiment experiment-ykokiuc0p2.
PASSED
tests/test_sanity_portforward.py::TestSanity::test_katib_experiment PASSEDkeep Success Option for Installation:
True


======================================================================== 3 passed in 1669.65s (0:27:49) =========================================================================
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jsitu777** [comment]
https://github.com/awslabs/kubeflow-manifests/pull/351
refer to here for unit test.

**Review by rrrkharse — CHANGES_REQUESTED** [review]
can you include your integ test changes and a readme with how to install helm?

**Comment by jsitu777** [comment]
@rrrkharse 
The integration test change I am going to include it in a separate PR. But here's a summary of what I changed:
    -replace the kustomize.py fixture with a installation.py fixture so helm can be triggered by a new parser called installation_option (by default it's kustomize). In the on_create and on_delete functions, they will be replaced by the install_kubeflow and uninstall_kubeflow functions instead of the existing lambda while loop function
```
def on_create():
        install_kubeflow(installation_option, aws_telemetry_option, deployment_option)

 def on_delete():
        print("keep Success Option for Installation:")
        print(keep_successfully_created_resource(request))
        if keep_successfully_created_resource(request) == False:
            print("Start to Uninstall KubeFlow...")
            uninstall_kubeflow(installation_option, aws_telemetry_option, deployment_option)
```
    
    -Added some parsers in conftest.py: 
        *aws_telemetry_option (default enable)
        *deployment_option (default vanilla)
        *installation_option (default kustomize)
    -Added a new parser --deletecluster inaddition to --keepsuccess
        *cluster will not be deleted unless you put in --deletecluster

To use helm installation, just run the installation script 
```
PYTHONPATH=.. python utils/kubeflow_installation.py --installation_option helm
```

for other deployment options:
Cognito
```
PYTHONPATH=.. python utils/kubeflow_installation.py --installation_option helm --deployment_option cognito
```
RDS-and-S3:
```
PYTHONPATH=.. python utils/kubeflow_installation.py --installation_option helm --deployment_option rds-and-s3
```
RDS-only:
```
PYTHONPATH=.. python utils/kubeflow_installation.py --installation_option helm --deployment_option rds-only
```
S3-only:
```
PYTHONPATH=.. python utils/kubeflow_installation.py --installation_option helm --deployment_option s3-only
```

Cert-manager and AWS-Load-Balancer will be from official helm charts repo:
```
helm install cert-manager jetstack/cert-manager \
                        --namespace cert-manager \
                        --create-namespace \
                        --version v1.9.1 \
                        --set installCRDs=true
```

```
helm repo add eks https://aws.github.io/eks-charts

helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=<cluster-name> --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller
```

**Review by surajkota — CHANGES_REQUESTED** [review]
can we remove the .helmignore from all the charts?
Its used while packaging and we are not packaging the charts.

Also we should not release this with the current versions and appVersions in chart.yaml. It will have implications for future releases. Ok to merge this PR but we need figure out what is the right approach.

Should the chart version be a combination of each component version as defined in https://github.com/kubeflow/manifests#kubeflow-components-versions and aws release version? or just aws build number for each release? Chart version should be a semver2 so you would have to use either the pre release or build identifier format

Even if we leave out upgrade scenarios, what is the path for patch and minor version releases? with kustomize customer can build and apply new manifests. What is the experience with helm? Doesnt the chart version need to be changed for a new release?


I have reviewed this on a high level. It is impossible to look at 700+ files. Lets use unit tests and integration tests as mechanisms to validate these charts

**Comment by surajkota** [comment]
Awesome work on the autogeneration of charts! It is a great addition to the Kubeflow deployment.

Its good that you have already separated crds which will be useful while uninstalling

**Comment by jsitu777** [comment]
> can we remove the .helmignore from all the charts? Its used while packaging and we are not packaging the charts.
> 
> Also we should not release this with the current versions and appVersions in chart.yaml. It will have implications for future releases. Ok to merge this PR but we need figure out what is the right approach.
> 
> Should the chart version be a combination of each component version as defined in https://github.com/kubeflow/manifests#kubeflow-components-versions and aws release version? or just aws build number for each release? Chart version should be a semver2 so you would have to use either the pre release or build identifier format
> 
> Even if we leave out upgrade scenarios, what is the path for patch and minor version releases? with kustomize customer can build and apply new manifests. What is the experience with helm? Doesnt the chart version need to be changed for a new release?
> 
> I have reviewed this on a high level. It is impossible to look at 700+ files. Lets use unit tests and integration tests as mechanisms to validate these charts

@surajkota just removed all the gitignore files

**Review by surajkota — CHANGES_REQUESTED** [review]
ok, last comment move the admission-webhook and profiles to apps instead of common.

lgtm otherwise. 2 more things left to do in follow up PR:

adding serviceaccount create = false option for profile controller 
and exposing central dashboard configmap vars to values.yaml

**Comment by jsitu777** [comment]
> ok, last comment move the admission-webhook and profiles to apps instead of common.
> 
> lgtm otherwise. 2 more things left to do in follow up PR:
> 
> adding serviceaccount create = false option for profile controller and exposing central dashboard configmap vars to values.yaml

Moved.

**Review by surajkota — APPROVED** [review]

**Review by rrrkharse — CHANGES_REQUESTED** [review]
Can you add the following folder and files to this PR: https://github.com/rrrkharse/kubeflow-manifests/tree/helm-chart-vanilla-v1.6.0/charts/utils

and run the script to split the vanilla kfp chart?

**Review by rrrkharse — APPROVED** [review]

**Pull request merged**
